name: Buf Deploy

on:
  push:
    branches:
      - main


concurrency: ${{ github.workflow }}


jobs:
  changed:
      name: Changed
      runs-on: ubuntu-latest
      outputs:
        changes: ${{ steps.identify_changes.outputs.src_count }}

      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4

        - name: Check Changes
          id: identify_changes
          run: |
            echo "src_count=$(git diff --name-only | grep src | wc -l)" >> $GITHUB_OUTPUT

        - name: Debug
          id: debug
          run: echo "DEBUG ${{ steps.identify_changes.outputs.src_count }}"

  deploy_schema_registry:
    if: ${{ needs.release-please.outputs.release && needs.release-please.outputs.changes >= 1 }}
    needs:
      - changed
    name: Buf Schema Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Masochist Scripts
        id: bsr_release
        uses: actions/checkout@v4
        with:
          repository: TimKotowski/masochist-scripts
          path: masochist-scripts
          token: ${{ secrets.GH_AUTO_MERGE }}

      - name: Run Buf Schema Registry Push
        uses: ./masochist-scripts/actions/buf_push
        with:
          token: ${{ secrets.BSR_TOKEN }}
          path: "src/proto3"
          gh_token: ${{ secrets.GH_API_TOKEN }}
          id: ${{ github.run_id }}
