name: Buf Deploy

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}

jobs:
  changed:
      name: Changed
      runs-on: ubuntu-latest
      outputs:
        changes: ${{ steps.identify_changes.outputs.src_count }}

      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Check Changes
          id: identify_changes
          run: |
            echo "src_count=$(git diff --name-only HEAD^ HEAD | grep src | wc -l)" >> $GITHUB_OUTPUT

  deploy_schema_registry:
    if: ${{ needs.changed.outputs.changes >= 1 }}
    needs:
      - changed
    name: Buf Schema Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Ci-Scripts
        id: bsr_release
        uses: actions/checkout@v4
        with:
          repository: TimKotowski/ci-scripts
          path: ci-scripts
          token: ${{ secrets.GH_AUTO_MERGE }}

      - name: Run Buf Schema Registry Push
        uses: ./ci-scripts/actions/buf_push
        with:
          token: ${{ secrets.BSR_TOKEN }}
          path: "src/proto3"
          gh_token: ${{ secrets.GH_API_TOKEN }}
          id: ${{ github.run_id }}
