name: Release

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs.release_created }}

    steps:
      - name: Release
        id: release
        uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_PLEASE_ACTION }}
          release-type: simple
          package-name: schema-registry
          version-file: version.txt
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          prerelease: true

  deploy_schema_registry:
    if: ${{ needs.release-please.outputs.release }}
    needs:
      - release-please
    name: Buf Schema Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Masochist Scripts
        id: bsr_release
        uses: actions/checkout@v4
        with:
          repository: TimKotowski/masochist-scripts
          path: masochist-scripts
          token: ${{ secrets.GH_AUTO_MERGE }}

      - name: Run Buf Schema Registry Push
        uses: ./masochist-scripts/actions/buf_push
        with:
          token: ${{ secrets.BSR_TOKEN }}
          path: "src/proto3"
          gh_token: ${{ secrets.GH_API_TOKEN }}
