on:
  pull_request:
    branches: [ "main" ]


jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_ACTION }}
          release-type: simple
          package-name: schema-registry
          version-file: version.txt
          bump-patch-for-minor-pre-major: true
  use:
    name: Use
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - name: Print Release Output
        run: |
          echo "Release PR: ${{ needs.release-please.outputs.release }}"